/**
 * JAANartc
 * JAANartc OpenAPI Documentations
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewTodoParams {
    title: string;
    content: string;
    priorityLevel?: NewTodoParams.PriorityLevelEnum;
}
export namespace NewTodoParams {
    export type PriorityLevelEnum = 'Low' | 'Medium' | 'High';
    export const PriorityLevelEnum = {
        Low: 'Low' as PriorityLevelEnum,
        Medium: 'Medium' as PriorityLevelEnum,
        High: 'High' as PriorityLevelEnum
    }
}
