/**
 * JAANartc
 * JAANartc OpenAPI Documentations
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TodoVm } from './todoVm';


export interface TodoResponse {
    status?: number;
    result?: TodoVm;
}
